### ISSUE TITLE
Copy-paste error in tagger implementation

### ISSUE THREAD

**Issue by ZhanruiLiang** [jacksonllee/pycantonese#34]
**Describe the bug**
Code location:
https://github.com/jacksonllee/pycantonese/blob/main/src/pycantonese/pos_tagging/tagger.py#L262
From the context, i+2 should be used but it has i-2 currently.
I tried to fix and and regen the model pickle file, but that fails some tests which I don't know how to proceed.

**To reproduce**
* Change i-2 to i+2 in the linked line and the line below.
* Regenerate model by running train_tagger.py
* Run tests `python -m pytest tests/test_parsing.py

**Expected behavior**
All tests pass.

**System (please complete the following information):**
 - Operating System: MacOS
 - PyCantonese version: 3.4.0

**Comment by jacksonllee** [comment]
I've resolved this issue at the `main` branch. Some of the tests got upset due to noise in the training data from HKCanCor -- that's been fixed as well.

You've been [acknowledged in the readme](https://github.com/jacksonllee/pycantonese#acknowledgments). Thank you for reporting this issue!
