### ISSUE TITLE
`hkcancor_to_ud` typo: "G1": "V" should be "VERB"

### ISSUE THREAD

**Issue by AlienKevin** [jacksonllee/pycantonese#48]
The `_MAP` for the `pos_tagging.hkcancor_to_ud` function has a typo that incorrectly outputs the `V` as a UD tag when `VERB` is intended. This breaks downstream tasks that rely on pycantonese to convert hkcancor labels into UD.

**Comment by jacksonllee** [comment]
@AlienKevin Thank you for catching the typo and creating this issue! I've just fixed it at the upstream `main` branch, so for now you can get the fixed pycantonese package by installing it from the github source:

```
pip install git+https://github.com/jacksonllee/pycantonese.git
```
